name: Package and release

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Extract current version changelog
        run: |
          awk 'f&&/^## /{exit} /^## /{f=1;next} f{print}' CHANGELOG.md > CHANGELOG_current.md
          cat CHANGELOG_current.md

      - name: Package and release
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}